<a href="https://colab.research.google.com/github/LalitSharma7/Data-Science-Roadmap/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [x*10 for x in range(1,11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
my_array.ndim

1

In [ ]:
my_array.shape

(10,)

In [ ]:
my_array.size

10

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(2, dtype = 'int')

array([1, 1])

In [ ]:
np.zeros((5,20), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
rng = np.random.default_rng(235)
rng.random(10)

array([0.49892245, 0.07012218, 0.06637254, 0.10008367, 0.89475702,
       0.35125843, 0.83667146, 0.35868797, 0.61981314, 0.77153624])

In [ ]:
int_array = np.arange(12)
int_array[4]

4

In [ ]:
int_array[-2]

10

In [ ]:
int_array[:5]

array([0, 1, 2, 3, 4])

In [ ]:
rng = np.random.default_rng(235)
invet = rng.integers(0,100,10)
invet

array([67, 49, 99,  7, 20,  6, 71, 10, 41, 89])

In [ ]:
invet - 20

array([ 47,  29,  79, -13,   0, -14,  51, -10,  21,  69])

In [ ]:
price = (rng.random(11)*10).round(2)
price

array([3.51, 8.37, 3.59, 6.2 , 7.72, 7.  , 5.5 , 9.87, 1.91, 7.76, 5.29])

In [ ]:
arr = np.arange(20)
arr
arr%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
even_odd = np.array(['even', 'odd']*10)
even_odd


array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
even_odd[even_odd!='odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [ ]:
arr[even_odd!='odd'] =0
arr

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [ ]:
np.where(arr%2==0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
arr.sum()

100

In [ ]:
arr.mean()

5.0

In [ ]:
arr.min()

0

In [ ]:
arr.argmax()

19

In [ ]:
np.median(arr)

0.5

In [ ]:
arr

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [ ]:
np.percentile(arr, 90)

15.200000000000003

In [ ]:
arr.sort()
arr
np.median(arr)

0.5

In [ ]:
np.sqrt(arr)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])